### ISSUE TITLE
Battery life and other questions...

### ISSUE THREAD

**Issue by oybekrustamov** [jianminglok/E5-576G-Hackintosh#1]
Hi dear! Can you tell me? I have a few questions..
I have Acer Aspire e5-576g (core i3 7020u, HD620 + MX130, 12GB RAM)
I did everything, disabled the discrete video card using Whatevergreen.. All I think configured, but the battery is barely enough for 2 hours, but I have Windows running for about 5 hours. Can you help with this? 
At the moment, I am using Windows. I want to install Catalina 15.4. Thank you...

**Comment by oybekrustamov** [comment]
and when I download a Hackintosh without a connected USB wifi, it is not recognized by the system after connecting. You need to connect it to a disabled laptop, then it will work.. What should I do?

**Comment by jianminglok** [comment]
> Hi dear! Can you tell me? I have a few questions..
> I have Acer Aspire e5-576g (core i3 7020u, HD620 + MX130, 12GB RAM)
> I did everything, disabled the discrete video card using Whatevergreen.. All I think configured, but the battery is barely enough for 2 hours, but I have Windows running for about 5 hours. Can you help with this?
> At the moment, I am using Windows. I want to install Catalina 15.4. Thank you...

Since you are using a different processor, The CPUFriendDataProvider.kext is not suitable as the data is for i5-8250U instead. Follow the CPUFriendFriend guide here to generate a kext for your processor. 

`https://1revenger1.gitbook.io/laptop-guide/battery-power-management/optimizing-battery-life`

> and when I download a Hackintosh without a connected USB wifi, it is not recognized by the system after connecting. You need to connect it to a disabled laptop, then it will work.. What should I do?

Well if you mean the USB wifi adapter/dongle doesn't work immediately after you plug in it, I have no idea too. I normally plug in it and then restart to get it working.

**Comment by oybekrustamov** [comment]
Thanks for the answer. And after applying CPUFriend, it will work normally (well, automatically manage as in Windows my processor?)
And if it's not difficult for you, you can upload a video to YouTube. how did you configure the Bootloader?

**Comment by jianminglok** [comment]
> Thanks for the answer. And after applying CPUFriend, it will work normally (well, automatically manage as in Windows my processor?)
> And if it's not difficult for you, you can upload a video to YouTube. how did you configure the Bootloader?

Yes, it should work fine as long as you follow the guide correctly. Uploading a YouTube video isn't on my plan for now, but may I know what problems are you facing in configuring the bootloader?

**Comment by oybekrustamov** [comment]
> Yes, it should work fine as long as you follow the guide correctly. Uploading a YouTube video isn't on my plan for now, but may I know what problems are you facing in configuring the bootloader?

Actually, I only have problems with the battery (maximum 2 hours). I want somewhere 4-5 hours as in Windows :) The laptop is exactly the same, an exact copy. In addition to the processor, I have with the i3 series.

**Comment by jianminglok** [comment]
> Actually, I only have problems with the battery (maximum 2 hours). I want somewhere 4-5 hours as in Windows :) The laptop is exactly the same, an exact copy. In addition to the processor, I have with the i3 series.

If so, let me know if the battery issue is still there after you put in the kext you generated for your processor.

**Comment by oybekrustamov** [comment]
> If so, let me know if the battery issue is still there after you put in the kext you generated for your processor.

Well, I'll write to you. Thanks!

**Comment by oybekrustamov** [comment]
Hello dear friend, I just installed it, I just stayed in clover, could not configure OpenCore, it’s difficult for me. Included all AML files, kexts, drivers, + generated CPUFriend
chose 800mhz + optimal battery (default)
Now it’s normal so far, in 10 minutes 2% discharge ... If anything, ill write to you !! Thanks!
That would solve the problem with USB Wi-Fi without rebooting the system, it would be cool ... :)

**Comment by oybekrustamov** [comment]
I have a kernel panic. How can I fix it?
The panic:

> panic(cpu 2 caller 0xffffff8001616487): "IOSCSIPeripheralDeviceType05::setPowerState(0xffffff802c22ceb0 : 0xffffff7f81dc6236, 1 -> 4) timed out after 100676 ms"@/AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/xnu/xnu-6153.101.6/iokit/Kernel/IOServicePM.cpp:5296
Backtrace (CPU 2), Frame : Return Address
0xffffff8182e43b40 : 0xffffff8000f215cd mach_kernel : _handle_debugger_trap + 0x49d
0xffffff8182e43b90 : 0xffffff800105a3c5 mach_kernel : _kdp_i386_trap + 0x155
0xffffff8182e43bd0 : 0xffffff800104bf7e mach_kernel : _kernel_trap + 0x4ee
0xffffff8182e43c20 : 0xffffff8000ec7a40 mach_kernel : _return_from_trap + 0xe0
0xffffff8182e43c40 : 0xffffff8000f20c97 mach_kernel : _DebuggerTrapWithState + 0x17
0xffffff8182e43d40 : 0xffffff8000f21087 mach_kernel : _panic_trap_to_debugger + 0x227
0xffffff8182e43d90 : 0xffffff80016c2c7c mach_kernel : _panic + 0x54
0xffffff8182e43e00 : 0xffffff8001616487 mach_kernel : __ZN9IOService12ackTimerTickEv + 0x6f7
0xffffff8182e43e50 : 0xffffff8001615d69 mach_kernel : __ZN9IOService21actionAckTimerExpiredEP8OSObjectPvS2_S2_S2_ + 0x9
0xffffff8182e43e60 : 0xffffff800162d2fe mach_kernel : __ZN10IOWorkLoop9runActionEPFiP8OSObjectPvS2_S2_S2_ES1_S2_S2_S2_S2_ + 0x3e
0xffffff8182e43ea0 : 0xffffff8001614b18 mach_kernel : __ZN9IOService17ack_timer_expiredEPvS0_ + 0x38
0xffffff8182e43ec0 : 0xffffff8000f63545 mach_kernel : _thread_call_delayed_timer + 0xec5
0xffffff8182e43f40 : 0xffffff8000f63071 mach_kernel : _thread_call_delayed_timer + 0x9f1
0xffffff8182e43fa0 : 0xffffff8000ec713e mach_kernel : _call_continuation + 0x2e

BSD process name corresponding to current thread: kernel_task
Boot args: -v debug=0x100 keepsyms=1

**Comment by jianminglok** [comment]
> I have a kernel panic. How can I fix it?
> The panic:
> 
> > panic(cpu 2 caller 0xffffff8001616487): "IOSCSIPeripheralDeviceType05::setPowerState(0xffffff802c22ceb0 : 0xffffff7f81dc6236, 1 -> 4) timed out after 100676 ms"@/AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/xnu/xnu-6153.101.6/iokit/Kernel/IOServicePM.cpp:5296
> > Backtrace (CPU 2), Frame : Return Address
> > 0xffffff8182e43b40 : 0xffffff8000f215cd mach_kernel : _handle_debugger_trap + 0x49d
> > 0xffffff8182e43b90 : 0xffffff800105a3c5 mach_kernel : _kdp_i386_trap + 0x155
> > 0xffffff8182e43bd0 : 0xffffff800104bf7e mach_kernel : _kernel_trap + 0x4ee
> > 0xffffff8182e43c20 : 0xffffff8000ec7a40 mach_kernel : _return_from_trap + 0xe0
> > 0xffffff8182e43c40 : 0xffffff8000f20c97 mach_kernel : _DebuggerTrapWithState + 0x17
> > 0xffffff8182e43d40 : 0xffffff8000f21087 mach_kernel : _panic_trap_to_debugger + 0x227
> > 0xffffff8182e43d90 : 0xffffff80016c2c7c mach_kernel : _panic + 0x54
> > 0xffffff8182e43e00 : 0xffffff8001616487 mach_kernel : __ZN9IOService12ackTimerTickEv + 0x6f7
> > 0xffffff8182e43e50 : 0xffffff8001615d69 mach_kernel : __ZN9IOService21actionAckTimerExpiredEP8OSObjectPvS2_S2_S2_ + 0x9
> > 0xffffff8182e43e60 : 0xffffff800162d2fe mach_kernel : __ZN10IOWorkLoop9runActionEPFiP8OSObjectPvS2_S2_S2_ES1_S2_S2_S2_S2_ + 0x3e
> > 0xffffff8182e43ea0 : 0xffffff8001614b18 mach_kernel : __ZN9IOService17ack_timer_expiredEPvS0_ + 0x38
> > 0xffffff8182e43ec0 : 0xffffff8000f63545 mach_kernel : _thread_call_delayed_timer + 0xec5
> > 0xffffff8182e43f40 : 0xffffff8000f63071 mach_kernel : _thread_call_delayed_timer + 0x9f1
> > 0xffffff8182e43fa0 : 0xffffff8000ec713e mach_kernel : _call_continuation + 0x2e
> 
> BSD process name corresponding to current thread: kernel_task
> Boot args: -v debug=0x100 keepsyms=1

Unfortunately I also have no idea only how to fix it, I would suggest you to try asking for help on other forums. Good luck! I'll close this issue for now.
