### ISSUE TITLE
Bootcamp

### ISSUE THREAD

**Issue by techgenius1** [jianminglok/E5-576G-Hackintosh#4]
I tried to install bootcamp and everything was totally fine but after booting windows from open core it gives bluescreen (ACPI BIOS ERROR) but if i boot it from windows boot manager it boots up. So probably some SSDT patch or config is broking  windows because i was using my own EFI folder before and everything with bootcamp works fine but your EFI folder build is very well optimized for mac os. So Please fix windows bluescreen with open core

**Comment by jianminglok** [comment]
Please upload your previous EFI folder if possible as it would greatly help in the debugging process.

Thank you.

**Comment by techgenius1** [comment]
> Please upload your previous EFI folder if possible as it would greatly help in the debugging process.
> 
> Thank you.

Here it is, but my touchpad wasnt working on that EFI
https://drive.google.com/file/d/1Fsfy237oMqYPBn3nCVqS0Ixldyc8HLHE/view?usp=drivesdk

**Comment by jianminglok** [comment]
You may try the latest commit 7148f54 to see if you can now boot Windows. Just tried and it seems to be working fine for me.

**Comment by techgenius1** [comment]
Okay thanks i will try it tomorrow and also where can i chat with you ?

**Comment by jianminglok** [comment]
We can just continue the discussion here, if you're still facing any other issues

**Comment by techgenius1** [comment]
Windows booting is works now thanks, also you can remove refind files from efi and bootstrap folders.
