### ISSUE TITLE
TPD1 device ssdt patch

### ISSUE THREAD

**Issue by techgenius1** [jianminglok/E5-576G-Hackintosh#5]
I have TPD1 device as I2C touchpad, pin number is totally same and it works fine with current kexts. I modified TPDE ssdt patch to TPD1 but you can also include TPD1 in TPDE ssdt patch so both will work on any E5-576G

**Comment by jianminglok** [comment]
May I know what model is your E5-576G?

**Comment by techgenius1** [comment]
> May I know what model is your E5-576G?

Acer E5-576G-59S6

**Comment by jianminglok** [comment]
You may check the latest commit.

**Comment by techgenius1** [comment]
Thanks
