### ISSUE TITLE
OCS: No Scheme for DeDuplicateBootOrder

### ISSUE THREAD

**Issue by techgenius1** [jianminglok/E5-576G-Hackintosh#6]
I Started to see that error while OpenCore comes but it happens in half of a second so i hardly see that error 
`OCS: No Scheme for DeDuplicateBootOrder at 0 Index, context <Quirks> | `

**Comment by kirylrb** [comment]
@techgenius1 Opencore 0.6.5 release notes - Removed no longer required DeduplicateBootOrder quirk

**Comment by jianminglok** [comment]
This issue is now fixed with the latest commit

**Comment by techgenius1** [comment]
Thanks problem solved
