### ISSUE TITLE
Acer E5-576G-59S6 Diffrent PCI devices / Device Paths

### ISSUE THREAD

**Issue by techgenius1** [jianminglok/E5-576G-Hackintosh#9]
I Pulled my PCI device paths to attached config I just added iGPU patches but i didn't do anything else, so can you check if there is anything needed to do or patch about PCI devices here. Or i should keep using your device paths ? 
[config_59S6.plist.zip](https://github.com/jianminglok/E5-576G-Hackintosh/files/5861308/config_59S6.plist.zip)

**Comment by techgenius1** [comment]
Any Update about issue ?

**Comment by jianminglok** [comment]
As long as it works I don't see any need to modify it.

**Comment by techgenius1** [comment]
I modified some paths and works fine also forked this repo and updated everything added 2 new kexts for thermal subsystem and SMBus that shown as kext doesnt loaded.
here is forked repo link: [Acer-E5-576G-59S6-Hackintosh-OC](https://github.com/techgenius1/Acer-E5-576G-59S6-Hackintosh-OC) 
You may want to update Readme file for installing and current status part.
